Vagrant.configure("2") do |config|
  # Pick any base box you like
  config.vm.box = "centos/stream9"

  # Set the desired disk size
  config.disksize.size = "100GB"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos-test"
    vb.cpus = 2
    vb.memory = 4096
  end
end
