name: CI with Tag Filtering and Allure Report

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to Run (e.g., @Books, @authors)'
        required: false
        default: '@AllAPIs'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ALLURE_RESULTS_DIR: allure-results
      ALLURE_REPORT_DIR: allure-report

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests by Tags
        run: mvn clean test -Dcucumber.filter.tags="${{ github.event.inputs.tags }}"

      - name: Install Allure CLI
        run: |
          curl -Lo allure.tgz https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -xzvf allure.tgz
          sudo mv allure-2.34.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate $ALLURE_RESULTS_DIR --clean -o $ALLURE_REPORT_DIR

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ${{ env.ALLURE_REPORT_DIR }}

      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.ALLURE_REPORT_DIR }}
